[package]
name = "pixel-sort-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
web-sys = { version = "0.3", features = ["console", "Window", "Document", "Element"] }
wasm-bindgen = "0.2"
